import { parseNationId } from "../../../shared/ids";
import { getScenarioAdjacency } from "../adjacency";
import type { ProvinceDefinition, ProvinceTerrain } from "../registry";

const adjacency = getScenarioAdjacency("scn_ea1900");

const province = (
  id: string,
  nationId: string,
  population: number,
  nameKo: string,
  terrain: ProvinceTerrain,
  developmentBps: number,
  isCapital: boolean,
  isPort: boolean,
): ProvinceDefinition =>
  Object.freeze({
    id,
    ownerNationId: parseNationId(nationId),
    population,
    nameKo,
    adjacentProvinceIds: Object.freeze([...(adjacency[id] ?? [])]),
    isCapital,
    isPort,
    terrain,
    developmentBps,
  });

export const eastAsiaProvinces: readonly ProvinceDefinition[] = Object.freeze([
  province("prv_kor_hanseong", "nat_kor", 1_200_000, "한성", "plain", 3_400, true, true),
  province("prv_kor_gyeonggi", "nat_kor", 2_200_000, "경기", "coast", 2_900, false, true),
  province("prv_kor_pyeongan", "nat_kor", 2_300_000, "평안", "mountain", 2_100, false, true),
  province("prv_kor_hamgyeong", "nat_kor", 1_500_000, "함경", "mountain", 1_700, false, true),
  province("prv_kor_chungcheong", "nat_kor", 2_700_000, "충청", "plain", 2_200, false, false),
  province("prv_kor_jeolla", "nat_kor", 3_500_000, "전라", "coast", 2_300, false, true),
  province("prv_kor_gyeongsang", "nat_kor", 3_682_000, "경상", "mountain", 2_600, false, true),
  province("prv_jpn_hokkaido", "nat_jpn", 3_000_000, "홋카이도", "forest", 3_200, false, true),
  province("prv_jpn_tohoku", "nat_jpn", 5_000_000, "도호쿠", "mountain", 3_800, false, true),
  province("prv_jpn_kanto", "nat_jpn", 10_000_000, "간토", "plain", 6_500, true, true),
  province("prv_jpn_chubu", "nat_jpn", 6_000_000, "주부", "mountain", 4_700, false, true),
  province("prv_jpn_kansai", "nat_jpn", 8_000_000, "간사이", "plain", 6_000, false, true),
  province(
    "prv_jpn_chugoku_shikoku",
    "nat_jpn",
    5_000_000,
    "주고쿠·시코쿠",
    "coast",
    4_500,
    false,
    true,
  ),
  province("prv_jpn_kyushu", "nat_jpn", 6_850_000, "규슈", "coast", 4_800, false, true),
  province("prv_qing_manchuria", "nat_qing", 45_000_000, "만주", "forest", 1_900, false, true),
  province("prv_qing_zhili", "nat_qing", 60_000_000, "직례", "plain", 2_800, true, true),
  province("prv_qing_shandong", "nat_qing", 35_000_000, "산둥", "coast", 2_300, false, true),
  province("prv_qing_jiangnan", "nat_qing", 85_000_000, "강남", "coast", 3_500, false, true),
  province("prv_qing_central", "nat_qing", 70_000_000, "중부", "plain", 2_000, false, false),
  province("prv_qing_south", "nat_qing", 55_000_000, "남부", "plain", 2_200, false, true),
  province("prv_qing_west", "nat_qing", 50_000_000, "서부", "mountain", 900, false, false),
  province("prv_rus_primorye", "nat_rus", 2_000_000, "연해주", "coast", 2_000, false, true),
  province("prv_rus_amur", "nat_rus", 1_500_000, "아무르", "forest", 1_300, false, false),
  province(
    "prv_rus_transbaikal",
    "nat_rus",
    3_000_000,
    "자바이칼",
    "mountain",
    1_200,
    false,
    false,
  ),
  province("prv_rus_core", "nat_rus", 129_500_000, "러시아 본토", "forest", 4_200, true, true),
  province("prv_gbr_hongkong", "nat_gbr", 300_000, "홍콩", "coast", 7_000, true, true),
  province("prv_gbr_burma", "nat_gbr", 10_000_000, "버마", "forest", 1_900, false, true),
  province("prv_gbr_malaya", "nat_gbr", 2_000_000, "말라야", "coast", 3_000, false, true),
  province("prv_fra_indochina", "nat_fra", 15_000_000, "인도차이나", "coast", 2_400, true, true),
  province("prv_deu_qingdao", "nat_deu", 200_000, "칭다오", "coast", 4_500, true, true),
  province("prv_deu_pacific", "nat_deu", 500_000, "독일령 태평양", "coast", 1_800, false, true),
  province("prv_usa_philippines", "nat_usa", 7_000_000, "필리핀", "coast", 2_600, true, true),
  province(
    "prv_nld_east_indies",
    "nat_nld",
    38_000_000,
    "네덜란드령 동인도",
    "coast",
    2_700,
    true,
    true,
  ),
  province("prv_tha_siam", "nat_tha", 8_000_000, "시암", "plain", 2_000, true, true),
]);
