const provinceLabelsKo: Readonly<Record<string, string>> = Object.freeze({
  prv_rus_core: "러시아 본토",
  prv_rus_transbaikal: "자바이칼",
  prv_rus_amur: "아무르",
  prv_rus_primorye: "연해주",
  prv_qing_manchuria: "만주",
  prv_qing_zhili: "직례",
  prv_qing_shandong: "산둥",
  prv_qing_jiangnan: "강남",
  prv_qing_central: "중부",
  prv_qing_south: "남부",
  prv_qing_west: "서부",
  prv_kor_hamgyeong: "함경",
  prv_kor_pyeongan: "평안",
  prv_kor_hanseong: "한성",
  prv_kor_gyeonggi: "경기",
  prv_kor_chungcheong: "충청",
  prv_kor_jeolla: "전라",
  prv_kor_gyeongsang: "경상",
  prv_jpn_hokkaido: "홋카이도",
  prv_jpn_tohoku: "도호쿠",
  prv_jpn_kanto: "간토",
  prv_jpn_chubu: "주부",
  prv_jpn_kansai: "간사이",
  prv_jpn_chugoku_shikoku: "주고쿠·시코쿠",
  prv_jpn_kyushu: "규슈",
});

export const provinceNameKo = (provinceId: string): string =>
  provinceLabelsKo[provinceId] ?? provinceId;
