import { historicalPolityId } from "../../shared/historical-map-contract";
import type { NationProfileDefinition, NationTag } from "./registry";

export interface MajorPolity {
  readonly sourceName: string;
  readonly nameKo: string;
  readonly capitalLabelKo: string;
  readonly bloc: string;
  readonly population: number;
  readonly treasuryCredits: number;
  readonly stabilityBps: number;
  readonly manpowerPool: number;
  readonly profile: NationProfileDefinition;
  readonly governmentKo: string;
  readonly tags: readonly NationTag[];
}

const governmentFor = (sourceName: string, nameKo: string, bloc: string): string => {
  if (/USSR|East Germany|Cuba/.test(sourceName)) return "사회주의 공화제";
  if (sourceName === "China" && /중화인민/.test(nameKo)) return "사회주의 공화제";
  if (sourceName === "Germany" && bloc === "axis") return "일당독재제";
  if (/United Kingdom|Empire of Japan|Italy$|Japan$/.test(sourceName)) return "입헌군주제";
  if (/United States|Republic|Poland|Chinese warlords|West Germany/.test(sourceName)) {
    return "공화제";
  }
  if (
    /France|Germany|Brazil|India|Russia|Korea, Republic of|China/.test(sourceName) &&
    /allies|west|atlantic|nonaligned|pacific|eurasian|continental/.test(bloc)
  ) {
    return "공화제";
  }
  if (/Dutch Republic|England and Ireland/.test(sourceName)) return "공화제";
  if (/city-states|chiefdoms/.test(sourceName)) return "도시국가 연맹";
  if (/Sultanate|Caliphate|Mamluke/.test(sourceName)) return "술탄제";
  if (/Shogun|Shogunate/.test(sourceName)) return "막부제";
  if (/Khanate|Mongol/.test(sourceName)) return "칸국제";
  return "군주제";
};

const tagsFor = (sourceName: string): readonly NationTag[] => {
  const tags: NationTag[] = ["great_power"];
  if (/British|United Kingdom|Dutch|England|Spain|Portugal|France/.test(sourceName)) {
    tags.push("colonial");
  }
  if (/Empire|Khanate|Sultanate|Germany|USSR|United States|China|Russia/.test(sourceName)) {
    tags.push("expansionist");
  }
  if (/Song|Byzantine|Phrygians|Meroe|East Germany/.test(sourceName)) tags.push("declining");
  if (/Korea|Goryeo|Japan|Germany|India|Brazil/.test(sourceName)) tags.push("reformist");
  if (/Tokugawa|Fujiwara/.test(sourceName)) tags.push("isolationist");
  return Object.freeze([...new Set(tags)]);
};

const polity = (
  sourceName: string,
  nameKo: string,
  capitalLabelKo: string,
  bloc: string,
  population: number,
  treasuryCredits: number,
  stabilityBps: number,
  manpowerPool: number,
  strategicGoalKo: string,
  personalityKo: string,
): MajorPolity =>
  (() => {
    const governmentKo = governmentFor(sourceName, nameKo, bloc);
    return Object.freeze({
      sourceName,
      nameKo,
      capitalLabelKo,
      bloc,
      population,
      treasuryCredits,
      stabilityBps,
      manpowerPool,
      governmentKo,
      tags: tagsFor(sourceName),
      profile: Object.freeze({
        goalsKo: Object.freeze([`${nameKo}의 핵심 영토와 정통성을 보전한다`, strategicGoalKo]),
        personalityKo,
        rivalNationIds: Object.freeze([]),
        allyNationIds: Object.freeze([]),
      }),
    });
  })();

const overlays = Object.freeze({
  scn_bronze_1200bc: [
    polity(
      "Assyria",
      "앗시리아",
      "아슈르",
      "mesopotamia",
      800_000,
      460,
      6_200,
      80_000,
      "티그리스 상류의 교역로와 조공권을 장악한다",
      "전차군과 공납 체계를 앞세워 빠른 복속을 추구한다.",
    ),
    polity(
      "Babylonia",
      "바빌로니아",
      "바빌론",
      "mesopotamia",
      1_000_000,
      520,
      6_000,
      65_000,
      "유프라테스 수로와 남부 도시들의 결속을 회복한다",
      "관개 경제와 오래된 도시 권위를 지키는 신중한 왕국이다.",
    ),
    polity(
      "Egypt",
      "이집트 신왕국",
      "테베",
      "nile",
      3_000_000,
      900,
      7_200,
      180_000,
      "나일 계곡을 통합하고 레반트의 완충 지대를 유지한다",
      "풍부한 농업 기반과 신왕국의 권위를 믿는 방어적 강국이다.",
    ),
    polity(
      "Greek city-states",
      "에게 도시국가",
      "미케네",
      "aegean",
      750_000,
      430,
      5_400,
      55_000,
      "에게 해상로를 지키고 도시국가 간 연합을 재건한다",
      "분권적인 귀족 전사들이 해상 교역과 국지전을 병행한다.",
    ),
    polity(
      "Phrygians",
      "프리기아 왕국",
      "고르디온",
      "anatolia",
      400_000,
      260,
      4_300,
      30_000,
      "아나톨리아 고원의 통행로와 농경지를 확보한다",
      "이주와 권력 재편 속에서 생존을 우선하는 불안정한 왕국이다.",
    ),
    polity(
      "Kingdom of David and Solomon",
      "이스라엘 왕국",
      "예루살렘",
      "levant",
      350_000,
      230,
      6_000,
      25_000,
      "예루살렘 중심의 산악 왕국과 대상로를 결속한다",
      "제한된 자원으로 요새와 외교를 함께 활용하는 왕국이다.",
    ),
    polity(
      "Elam",
      "엘람",
      "수사",
      "iran",
      400_000,
      280,
      5_800,
      32_000,
      "수사와 자그로스 통로를 지키며 메소포타미아에 영향력을 행사한다",
      "산악 방어와 기회주의적 원정을 조합하는 오래된 왕국이다.",
    ),
    polity(
      "Kush",
      "쿠시 왕국",
      "나파타",
      "nile",
      200_000,
      180,
      6_400,
      18_000,
      "상나일의 금 산지와 대상 교역을 통제한다",
      "사막과 강의 지형을 이용해 독립을 지키는 남방 왕국이다.",
    ),
    polity(
      "Arameans",
      "아람 왕국군",
      "다마스쿠스",
      "levant",
      300_000,
      200,
      5_000,
      24_000,
      "시리아 내륙 도시와 대상로를 느슨한 동맹으로 묶는다",
      "도시별 자율성을 지키며 강대국 사이를 유연하게 오간다.",
    ),
    polity(
      "Urartu",
      "우라르투 왕국",
      "투시파",
      "anatolia",
      400_000,
      300,
      6_100,
      36_000,
      "반 호수의 요새망을 확장하고 북방 고원을 통합한다",
      "산악 요새와 중앙 집권을 중시하는 끈질긴 군사 왕국이다.",
    ),
  ],
  scn_classical_117: [
    polity(
      "Roman Empire",
      "로마 제국",
      "로마",
      "rome",
      65_000_000,
      2_300,
      6_800,
      1_800_000,
      "라인과 다뉴브 국경을 안정시키고 속주 조세망을 유지한다",
      "군단과 법제, 도로망으로 장기적인 질서를 구축하는 제국이다.",
    ),
    polity(
      "Han",
      "한 제국",
      "낙양",
      "han",
      55_000_000,
      2_100,
      5_700,
      1_500_000,
      "서역 교통로를 회복하고 북방 유목 세력을 억제한다",
      "관료제와 대규모 농업 기반을 가졌으나 궁정 균열을 경계한다.",
    ),
    polity(
      "Parthian Empire",
      "파르티아 제국",
      "크테시폰",
      "iran",
      10_000_000,
      900,
      6_200,
      350_000,
      "메소포타미아와 이란 고원의 귀족 연합을 유지한다",
      "기마 전력과 분권 귀족의 협상력을 활용하는 유연한 제국이다.",
    ),
    polity(
      "Kushan Empire",
      "쿠샨 제국",
      "푸루샤푸라",
      "silkroad",
      15_000_000,
      1_000,
      6_600,
      420_000,
      "인도와 중앙아시아를 잇는 비단길 관문을 장악한다",
      "다언어 상업권과 기병을 결합해 교역 안정에 투자한다.",
    ),
    polity(
      "Axum",
      "악숨 왕국",
      "악숨",
      "redsea",
      500_000,
      260,
      6_400,
      35_000,
      "홍해 항로와 아프리카 내륙 교역을 연결한다",
      "해상 교역과 고원 방어를 균형 있게 운용하는 신흥 왕국이다.",
    ),
    polity(
      "Armenia",
      "아르메니아 왕국",
      "아르타샤트",
      "caucasus",
      2_000_000,
      320,
      5_200,
      80_000,
      "로마와 파르티아 사이에서 왕국의 자율성을 보전한다",
      "산악 요새와 왕조 외교로 양대 제국 사이의 균형을 꾀한다.",
    ),
    polity(
      "Koguryo",
      "고구려",
      "국내성",
      "han",
      400_000,
      240,
      6_700,
      30_000,
      "압록강 유역의 성곽망을 넓히고 한 군현을 견제한다",
      "험준한 지형과 기동전을 활용해 점진적인 팽창을 노린다.",
    ),
    polity(
      "Maya chiefdoms and states",
      "마야 도시국가",
      "티칼",
      "mesoamerica",
      2_000_000,
      300,
      5_800,
      90_000,
      "저지대 교역망과 의례 중심지의 영향력을 확대한다",
      "경쟁하는 도시들이 동맹과 의례 전쟁을 반복하는 연합권이다.",
    ),
    polity(
      "Meroe",
      "메로에 왕국",
      "메로에",
      "nile",
      500_000,
      220,
      4_600,
      28_000,
      "상나일의 철 생산과 사막 교역로를 지킨다",
      "고립된 거점을 방어하며 교역 수입으로 버티는 왕국이다.",
    ),
  ],
  scn_medieval_1200: [
    polity(
      "Song Empire",
      "남송",
      "임안",
      "eastasia",
      60_000_000,
      1_900,
      4_400,
      900_000,
      "장강 경제권을 지키고 북방 상실지를 회복할 기반을 마련한다",
      "강한 상업과 관료제를 가졌지만 군사적 모험에는 신중한 왕조다.",
    ),
    polity(
      "Mongol Empire",
      "몽골 제국",
      "카라코룸",
      "steppe",
      1_000_000,
      620,
      7_800,
      180_000,
      "초원 부족을 통합하고 유라시아 정복로를 연다",
      "속도와 복종을 중시하며 저항 세력에는 단호한 기마 제국이다.",
    ),
    polity(
      "Goryeo",
      "고려",
      "개경",
      "eastasia",
      3_000_000,
      500,
      6_200,
      120_000,
      "북방 압력에 대비하며 해상 교역과 왕권을 강화한다",
      "문벌 질서를 지키되 외부 위협에는 실용적으로 대응하는 왕국이다.",
    ),
    polity(
      "Imperial Japan (Fujiwara)",
      "일본 조정",
      "헤이안쿄",
      "eastasia",
      7_000_000,
      650,
      5_400,
      180_000,
      "조정의 권위를 회복하고 지방 무사 세력을 통제한다",
      "의례적 정통성과 지방 세력의 협력에 의존하는 분권 왕조다.",
    ),
    polity(
      "Sultanate of Delhi",
      "델리 술탄국",
      "델리",
      "india",
      25_000_000,
      1_050,
      6_500,
      500_000,
      "북인도 요충지를 통합하고 변경의 반란을 억제한다",
      "기마 엘리트와 현지 행정을 결합해 빠른 확장을 추구한다.",
    ),
    polity(
      "Byzantine Empire",
      "비잔티움 제국",
      "콘스탄티노폴리스",
      "europe",
      6_000_000,
      600,
      4_200,
      150_000,
      "해협과 아나톨리아의 잔존 영토를 방어한다",
      "외교와 성곽에 능하지만 내부 분열을 경계하는 노련한 제국이다.",
    ),
    polity(
      "Holy Roman Empire",
      "신성 로마 제국",
      "아헨",
      "europe",
      12_000_000,
      800,
      4_900,
      300_000,
      "제후들의 충성을 확보하고 알프스 양편의 영향력을 유지한다",
      "협상과 봉건 동원을 통해 느슨한 제국 질서를 운용한다.",
    ),
    polity(
      "Kingdom of France",
      "프랑스 왕국",
      "파리",
      "europe",
      12_000_000,
      780,
      5_700,
      260_000,
      "왕령을 넓히고 경쟁 봉신에 대한 중앙 권력을 강화한다",
      "점진적인 영토 통합과 유력 봉신의 견제를 선호하는 왕국이다.",
    ),
    polity(
      "Chola state",
      "촐라 왕국",
      "강가이콘다촐라푸람",
      "india",
      5_000_000,
      550,
      6_000,
      140_000,
      "벵골만 해상로와 남인도 사원 경제를 보전한다",
      "함대와 상업 길드를 활용해 연안 영향력을 지키는 왕국이다.",
    ),
    polity(
      "Almohad Caliphate",
      "무와히드 칼리파국",
      "마라케시",
      "maghreb",
      8_000_000,
      650,
      5_200,
      190_000,
      "마그레브와 이베리아 영토의 결속을 회복한다",
      "종교적 정통성과 부족 동원을 바탕으로 반란을 억제한다.",
    ),
  ],
  scn_steppe_1300: [
    polity(
      "Great Khanate",
      "대칸국",
      "대도",
      "mongol",
      80_000_000,
      2_500,
      5_200,
      1_600_000,
      "중원의 세입을 확보하고 분열하는 칸국들에 종주권을 행사한다",
      "정복 왕조의 기동력과 중국식 행정을 함께 활용하는 대제국이다.",
    ),
    polity(
      "Khanate of the Golden Horde",
      "킵차크 칸국",
      "사라이",
      "mongol",
      6_000_000,
      750,
      6_700,
      220_000,
      "볼가 교역과 루스 공국의 공납 체계를 장악한다",
      "초원 기병과 간접 지배로 넓은 영역을 효율적으로 통제한다.",
    ),
    polity(
      "Ilkhanate",
      "일 칸국",
      "타브리즈",
      "mongol",
      8_000_000,
      850,
      5_600,
      240_000,
      "이란의 세입을 회복하고 메소포타미아 통치 기반을 다진다",
      "몽골 군사 귀족과 페르시아 관료 사이의 타협을 중시한다.",
    ),
    polity(
      "Chagatai Khanate",
      "차가타이 칸국",
      "알말리크",
      "mongol",
      4_000_000,
      520,
      6_100,
      150_000,
      "중앙아시아 오아시스와 초원 통행권을 유지한다",
      "유목 전통과 도시 세수를 함께 지키려는 균형적 칸국이다.",
    ),
    polity(
      "Mamluke Sultanate",
      "맘루크 술탄국",
      "카이로",
      "islam",
      6_000_000,
      720,
      6_500,
      180_000,
      "이집트와 시리아를 지키고 홍해 교역을 통제한다",
      "정예 기병과 요새선을 활용해 외부 침공에 단호히 대응한다.",
    ),
    polity(
      "Sultanate of Delhi",
      "델리 술탄국",
      "델리",
      "india",
      40_000_000,
      1_200,
      5_700,
      700_000,
      "갠지스 평원의 세입을 확보하고 변경 총독을 통제한다",
      "대규모 자원과 기마 군대를 가졌지만 지방 반란을 경계한다.",
    ),
    polity(
      "Byzantine Empire",
      "비잔티움 제국",
      "콘스탄티노폴리스",
      "europe",
      2_500_000,
      360,
      3_800,
      80_000,
      "콘스탄티노폴리스와 에게 해의 잔존 거점을 보전한다",
      "약해진 국력을 성곽과 외교로 보완하는 생존 중심 제국이다.",
    ),
    polity(
      "France",
      "프랑스 왕국",
      "파리",
      "europe",
      16_000_000,
      920,
      6_300,
      320_000,
      "왕권을 강화하고 플랑드르와 영국의 압력을 견제한다",
      "인구와 기사 동원을 바탕으로 꾸준한 중앙 집권을 추진한다.",
    ),
    polity(
      "Grand Duchy of Moscow",
      "모스크바 대공국",
      "모스크바",
      "rus",
      400_000,
      220,
      5_800,
      35_000,
      "인접 루스 공국을 규합하고 칸국 공납 부담을 줄인다",
      "신중한 공납 외교와 영토 매입으로 힘을 축적하는 공국이다.",
    ),
    polity(
      "Shogun Japan (Kamakura)",
      "가마쿠라 막부",
      "가마쿠라",
      "eastasia",
      7_000_000,
      600,
      4_700,
      160_000,
      "무사 봉신의 충성을 회복하고 열도 방위를 정비한다",
      "봉건적 합의와 해안 방어에 의존하는 보수적인 막부다.",
    ),
  ],
  scn_trade_1650: [
    polity(
      "Mughal Empire",
      "무굴 제국",
      "아그라",
      "asian",
      130_000_000,
      3_500,
      6_100,
      2_200_000,
      "인도 아대륙의 조세 기반을 통합하고 데칸을 안정시킨다",
      "막대한 세입과 포용적 궁정 정치로 장기 지배를 추구한다.",
    ),
    polity(
      "Ottoman Empire",
      "오스만 제국",
      "콘스탄티니예",
      "continental",
      25_000_000,
      2_400,
      6_500,
      650_000,
      "지중해와 흑해의 관문을 지키고 동서 국경을 안정시킨다",
      "관료제와 상비군을 바탕으로 다전선 균형을 관리하는 제국이다.",
    ),
    polity(
      "Safavid Empire",
      "사파비 제국",
      "이스파한",
      "continental",
      9_000_000,
      1_100,
      5_400,
      230_000,
      "이란 고원의 종교적 결속과 비단 교역을 보전한다",
      "왕조 정통성을 앞세우면서 오스만과의 소모전을 피하려 한다.",
    ),
    polity(
      "Dutch Republic",
      "네덜란드 공화국",
      "암스테르담",
      "maritime",
      1_900_000,
      1_900,
      7_300,
      95_000,
      "상선망과 동인도 무역 거점을 확대한다",
      "금융과 해군력을 결합해 제한된 인구의 약점을 보완한다.",
    ),
    polity(
      "England and Ireland",
      "잉글랜드 연방",
      "런던",
      "maritime",
      7_000_000,
      1_700,
      5_900,
      210_000,
      "내전 이후 국내 질서를 회복하고 대서양 함대를 강화한다",
      "의회와 군의 긴장을 안고도 해상 진출에는 적극적인 공화국이다.",
    ),
    polity(
      "France",
      "프랑스 왕국",
      "파리",
      "continental",
      20_000_000,
      2_100,
      6_300,
      400_000,
      "왕권을 강화하고 유럽 대륙의 합스부르크 포위를 해체한다",
      "인구와 육군을 기반으로 장기적인 대륙 우위를 노리는 왕국이다.",
    ),
    polity(
      "Spain",
      "스페인 왕국",
      "마드리드",
      "maritime",
      7_000_000,
      1_850,
      4_600,
      250_000,
      "아메리카 은 무역과 유럽 영토를 지켜 재정 쇠퇴를 막는다",
      "광대한 제국의 의무 때문에 선택과 집중이 필요한 군주국이다.",
    ),
    polity(
      "Portugal",
      "포르투갈 왕국",
      "리스본",
      "maritime",
      2_000_000,
      950,
      5_700,
      80_000,
      "브라질과 인도양 거점을 연결하는 항로를 보전한다",
      "좁은 본토의 한계를 동맹과 해상 거점으로 극복하려 한다.",
    ),
    polity(
      "Manchu Empire",
      "청 제국",
      "베이징",
      "asian",
      120_000_000,
      3_000,
      7_200,
      1_800_000,
      "중원 통치를 공고히 하고 남부 잔존 세력을 복속한다",
      "기병 팔기와 한인 관료제를 결합해 새 왕조의 안정을 추구한다.",
    ),
    polity(
      "Tokugawa Shogunate",
      "에도 막부",
      "에도",
      "asian",
      18_000_000,
      1_500,
      7_600,
      400_000,
      "다이묘 질서를 유지하고 제한된 대외 교역을 통제한다",
      "국내 평화와 신분 질서를 우선하는 안정 지향적 막부다.",
    ),
  ],
  scn_world_1939: [
    polity(
      "Germany",
      "독일국",
      "베를린",
      "axis",
      79_000_000,
      3_600,
      6_800,
      4_500_000,
      "폴란드를 고립시키고 유럽의 군사적 주도권을 장악한다",
      "재무장 성과를 과신하며 단기 결전과 위협 외교를 선호한다.",
    ),
    polity(
      "USSR",
      "소비에트 연방",
      "모스크바",
      "comintern",
      170_500_000,
      4_200,
      5_800,
      8_000_000,
      "서부 국경의 완충 지대를 확보하고 산업 동원을 완성한다",
      "대규모 자원과 중앙 통제를 믿지만 숙청 이후 지휘 혼선을 경계한다.",
    ),
    polity(
      "United States",
      "미합중국",
      "워싱턴",
      "allies",
      131_000_000,
      5_000,
      7_600,
      2_500_000,
      "양대양 방위를 강화하고 전쟁 억제를 위한 산업 역량을 확충한다",
      "국내 고립주의를 존중하면서 경제력으로 우방을 지원하려 한다.",
    ),
    polity(
      "United Kingdom",
      "대영제국",
      "런던",
      "allies",
      48_000_000,
      4_100,
      7_400,
      1_200_000,
      "유럽 세력 균형과 제국 해상로를 동시에 방어한다",
      "해군과 외교망을 활용해 적의 장기전을 유도하는 노련한 강국이다.",
    ),
    polity(
      "France",
      "프랑스 공화국",
      "파리",
      "allies",
      42_000_000,
      3_000,
      5_600,
      2_200_000,
      "독일의 팽창을 억제하고 동부 방어선을 유지한다",
      "강한 육군을 보유했지만 방어 교리와 정치 분열에 묶여 있다.",
    ),
    polity(
      "Empire of Japan",
      "일본제국",
      "도쿄",
      "axis",
      71_000_000,
      2_800,
      6_700,
      2_800_000,
      "중국 전선을 종결하고 자원 수입로를 확보한다",
      "군부의 영향 아래 빠른 확전을 택하지만 자원 부족에 민감하다.",
    ),
    polity(
      "Italy",
      "이탈리아 왕국",
      "로마",
      "axis",
      44_000_000,
      1_800,
      5_200,
      1_800_000,
      "지중해의 영향권을 넓히고 식민지 보급로를 지킨다",
      "대국의 위신을 추구하지만 산업과 보급의 한계를 안고 있다.",
    ),
    polity(
      "Poland",
      "폴란드 공화국",
      "바르샤바",
      "allies",
      35_000_000,
      1_200,
      6_100,
      1_300_000,
      "독일과 소련 사이에서 주권과 국경을 방어한다",
      "동맹 보장을 믿고 동서 양면의 압력에 단호히 맞서는 공화국이다.",
    ),
    polity(
      "British Raj",
      "영국령 인도",
      "뉴델리",
      "allies",
      380_000_000,
      2_600,
      4_900,
      2_000_000,
      "인도양 보급 기지와 제국 전시 동원을 유지한다",
      "거대한 인력 기반을 지녔지만 독립 운동과 제국 통치의 긴장이 크다.",
    ),
    polity(
      "Chinese warlords",
      "중화민국 군벌 연합",
      "충칭",
      "allies",
      510_000_000,
      1_600,
      3_900,
      8_000_000,
      "항일 전선을 유지하고 분열된 군벌 지휘를 통합한다",
      "압도적인 인구를 가졌지만 산업 부족과 내부 분열을 감수한다.",
    ),
  ],
  scn_coldwar_1962: [
    polity(
      "United States",
      "미합중국",
      "워싱턴",
      "west",
      186_000_000,
      6_000,
      7_600,
      4_000_000,
      "쿠바의 전략 무기를 제거하고 서방 동맹의 신뢰를 지킨다",
      "압도적인 경제력을 가졌지만 핵전쟁을 피할 출구도 함께 찾는다.",
    ),
    polity(
      "USSR",
      "소비에트 연방",
      "모스크바",
      "east",
      218_000_000,
      5_400,
      6_500,
      6_000_000,
      "쿠바의 동맹을 보호하고 미국의 전략 우위를 상쇄한다",
      "위험을 감수한 압박으로 협상력을 높이되 체제 생존을 우선한다.",
    ),
    polity(
      "China",
      "중화인민공화국",
      "베이징",
      "east",
      670_000_000,
      3_300,
      4_800,
      15_000_000,
      "자주 노선을 지키고 국경과 혁명 영향력을 강화한다",
      "대규모 동원을 신뢰하며 미소 양국 모두에 독자성을 주장한다.",
    ),
    polity(
      "United Kingdom",
      "영국",
      "런던",
      "west",
      53_000_000,
      3_000,
      6_900,
      900_000,
      "대서양 동맹과 독자 핵 억지력을 유지한다",
      "미국과 공조하면서 외교적 중재 공간을 확보하려 한다.",
    ),
    polity(
      "France",
      "프랑스",
      "파리",
      "west",
      47_000_000,
      2_800,
      6_200,
      1_000_000,
      "독자 핵전력과 유럽 내 전략적 자율성을 확보한다",
      "동맹 안에서도 독립적 판단과 국가 위신을 강하게 중시한다.",
    ),
    polity(
      "West Germany",
      "서독",
      "본",
      "west",
      57_000_000,
      2_500,
      7_000,
      750_000,
      "서방 통합을 지키고 베를린의 안전을 보장한다",
      "경제 성장과 동맹 억지에 의존하며 직접 충돌에는 신중하다.",
    ),
    polity(
      "East Germany",
      "동독",
      "동베를린",
      "east",
      17_000_000,
      1_300,
      5_200,
      350_000,
      "국경 통제를 유지하고 동구권 내 정권 안정을 확보한다",
      "강한 치안 통제로 이탈을 막지만 소련의 지원에 크게 의존한다.",
    ),
    polity(
      "India",
      "인도 공화국",
      "뉴델리",
      "nonaligned",
      450_000_000,
      1_900,
      5_900,
      7_000_000,
      "비동맹 자율성을 지키고 중국 국경 위기에 대응한다",
      "도덕적 외교와 실용적 방위를 함께 추구하는 신생 대국이다.",
    ),
    polity(
      "Japan",
      "일본국",
      "도쿄",
      "west",
      95_000_000,
      2_600,
      7_200,
      1_200_000,
      "경제 성장을 지속하고 미일 안보 체제를 안정시킨다",
      "군사 모험을 피하고 산업과 무역을 국력의 중심으로 삼는다.",
    ),
    polity(
      "Cuba",
      "쿠바 공화국",
      "아바나",
      "east",
      7_000_000,
      650,
      6_800,
      250_000,
      "혁명 정권의 생존과 미국 침공 억지를 확보한다",
      "봉쇄 속에서도 주권과 혁명 수호를 위해 높은 위험을 감수한다.",
    ),
  ],
  scn_modern: [
    polity(
      "Korea, Republic of",
      "대한민국",
      "서울",
      "atlantic",
      52_000_000,
      2_900,
      7_400,
      2_500_000,
      "한반도 억지력과 첨단 산업 공급망을 강화한다",
      "동맹을 중시하면서 기술과 무역으로 전략적 선택지를 넓힌다.",
    ),
    polity(
      "United States",
      "미합중국",
      "워싱턴",
      "atlantic",
      340_000_000,
      6_000,
      7_100,
      8_000_000,
      "동맹망과 해양 접근을 유지하며 경쟁국의 강압을 억제한다",
      "세계적 군사·금융 역량을 활용하되 동맹의 부담 분담을 요구한다.",
    ),
    polity(
      "China",
      "중화인민공화국",
      "베이징",
      "eurasian",
      1_410_000_000,
      5_800,
      6_900,
      20_000_000,
      "핵심 이익을 수호하고 유라시아 경제 영향력을 확대한다",
      "장기 계획과 국가 동원을 바탕으로 점진적인 세력 확대를 선호한다.",
    ),
    polity(
      "Russia",
      "러시아 연방",
      "모스크바",
      "eurasian",
      146_000_000,
      4_200,
      5_900,
      9_000_000,
      "서부 완충 지대와 에너지 수출 영향력을 보전한다",
      "군사력과 자원을 지렛대로 활용하며 외부 압박에 강경하게 대응한다.",
    ),
    polity(
      "Germany",
      "독일 연방공화국",
      "베를린",
      "atlantic",
      84_000_000,
      3_900,
      7_200,
      3_000_000,
      "유럽 통합과 산업 경쟁력을 지키며 에너지 취약성을 줄인다",
      "제도와 경제 협력을 우선하고 군사적 위험에는 신중한 강국이다.",
    ),
    polity(
      "United Kingdom",
      "영국",
      "런던",
      "atlantic",
      69_000_000,
      3_600,
      6_800,
      2_000_000,
      "대서양 안보와 세계 금융·해운 연결망을 유지한다",
      "동맹과 정보력을 활용해 제한된 자원으로 폭넓게 개입한다.",
    ),
    polity(
      "France",
      "프랑스 공화국",
      "파리",
      "atlantic",
      68_000_000,
      3_500,
      6_500,
      2_500_000,
      "유럽의 전략적 자율성과 해외 영향권을 유지한다",
      "독자 핵전력과 외교적 위신을 중시하는 개입적 공화국이다.",
    ),
    polity(
      "India",
      "인도 공화국",
      "뉴델리",
      "nonaligned",
      1_460_000_000,
      4_800,
      6_600,
      25_000_000,
      "국경 안보와 인도양 영향력을 강화하며 성장 기반을 확충한다",
      "전략적 자율성을 지키면서 사안별 협력을 택하는 실용적 대국이다.",
    ),
    polity(
      "Japan",
      "일본국",
      "도쿄",
      "atlantic",
      123_000_000,
      4_000,
      7_000,
      4_000_000,
      "해상 교통로와 첨단 산업을 지키며 방위 역량을 강화한다",
      "동맹과 경제력을 중시하면서 점진적으로 안보 역할을 넓힌다.",
    ),
    polity(
      "Brazil",
      "브라질 연방공화국",
      "브라질리아",
      "nonaligned",
      213_000_000,
      3_200,
      5_700,
      5_000_000,
      "남대서양 영향력과 아마존 주권을 지키며 산업을 다변화한다",
      "지역 주도권과 다자 외교를 선호하지만 국내 균형도 중시한다.",
    ),
  ],
  // 2281 assumes a 2090 demographic peak, regionally uneven collapse, and
  // roughly 0.5% annual recovery through 2281; the ten factions total ~1.47B.
  scn_reconstruction_2281: [
    polity(
      "China",
      "중화 재건국",
      "신베이징",
      "eurasian",
      310_000_000,
      5_000,
      6_100,
      12_000_000,
      "북부 수자원망을 복구하고 대륙 재건 회랑을 통제한다",
      "거대한 인구와 계획 경제로 장기 복구를 밀어붙이는 재건국이다.",
    ),
    polity(
      "Korea, Republic of",
      "한강 도시연합",
      "서울 메가폴리스",
      "pacific",
      88_000_000,
      4_200,
      7_600,
      3_500_000,
      "황해 방벽과 고밀도 도시망을 지키며 기술 교역을 확대한다",
      "도시 자치와 첨단 방재 체계를 결합한 민첩한 연합체다.",
    ),
    polity(
      "United States",
      "대서양 연방",
      "뉴 컬럼비아",
      "atlantic",
      280_000_000,
      5_200,
      6_500,
      10_000_000,
      "대서양 해상망을 복원하고 분산 정착지의 연방 결속을 유지한다",
      "자치 지역의 합의를 중시하면서 원거리 지원 능력을 재건한다.",
    ),
    polity(
      "Russia",
      "북방 연방",
      "노바 모스크바",
      "eurasian",
      120_000_000,
      4_000,
      5_500,
      7_000_000,
      "해빙 항로와 내륙 에너지 거점을 연결한다",
      "혹한 적응력과 자원 통제를 바탕으로 넓은 변경을 방어한다.",
    ),
    polity(
      "Germany",
      "라인 공동체",
      "베를린 돔",
      "continental",
      72_000_000,
      3_800,
      7_200,
      2_500_000,
      "유럽 제조 회랑과 에너지 순환망을 복구한다",
      "도시 공동체 간 규칙과 기술 표준으로 질서를 세우려 한다.",
    ),
    polity(
      "United Kingdom",
      "브리튼 해양령",
      "런던 방벽",
      "atlantic",
      54_000_000,
      3_400,
      6_700,
      1_800_000,
      "북해 방벽과 대서양 항로의 중계권을 지킨다",
      "섬의 방어 시설과 상선 네트워크를 활용하는 해양 세력이다.",
    ),
    polity(
      "France",
      "갈리아 코뮌",
      "파리 아르콜로지",
      "continental",
      61_000_000,
      3_500,
      6_900,
      2_000_000,
      "서유럽 농업권과 아르콜로지 간 배급망을 안정시킨다",
      "지역 코뮌의 합의를 통해 사회 안전망과 방위를 함께 운영한다.",
    ),
    polity(
      "India",
      "인더스 연합",
      "나바 델리",
      "nonaligned",
      260_000_000,
      4_500,
      6_200,
      11_000_000,
      "계절풍 수자원과 남아시아 이주 회랑을 관리한다",
      "다양한 지역 연합을 유지하며 식량과 물 안보를 최우선한다.",
    ),
    polity(
      "Japan",
      "열도 기술막부",
      "네오에도",
      "pacific",
      83_000_000,
      3_900,
      7_400,
      3_000_000,
      "부유식 도시와 태평양 자원망의 기술 우위를 보전한다",
      "폐쇄적인 기술 관료와 해양 상단이 정밀한 위험 관리를 선호한다.",
    ),
    polity(
      "Brazil",
      "아마존 생태연맹",
      "브라질리아 코어",
      "nonaligned",
      145_000_000,
      3_600,
      6_400,
      5_500_000,
      "아마존 생태 복구 구역과 남대서양 생물 자원을 보호한다",
      "생태 기술과 지역 민병대를 결합해 분산된 영토를 관리한다.",
    ),
  ],
} satisfies Readonly<Record<string, readonly MajorPolity[]>>);

export const historicalMajorPolities = (scenarioId: string): readonly MajorPolity[] => {
  const polities = overlays[scenarioId as keyof typeof overlays] ?? Object.freeze([]);
  return Object.freeze(
    polities.map((polity) => {
      const nationIdFor = (candidate: MajorPolity) =>
        historicalPolityId(historicalSovereignName(scenarioId, candidate.sourceName));
      const polityNationId = nationIdFor(polity);
      const otherPolities = polities.filter(
        (candidate) => candidate !== polity && nationIdFor(candidate) !== polityNationId,
      );
      const allyNationIds = [
        ...new Set(
          otherPolities.filter((candidate) => candidate.bloc === polity.bloc).map(nationIdFor),
        ),
      ];
      const rivalNationIds = [
        ...new Set(
          otherPolities.filter((candidate) => candidate.bloc !== polity.bloc).map(nationIdFor),
        ),
      ];
      return Object.freeze({
        ...polity,
        profile: Object.freeze({
          ...polity.profile,
          allyNationIds: Object.freeze(allyNationIds.slice(0, 3)),
          rivalNationIds: Object.freeze(rivalNationIds.slice(0, 2)),
        }),
      });
    }),
  );
};

const sovereignAliases: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.freeze({
  scn_medieval_1200: Object.freeze({ "Kingdom of France": "France" }),
  scn_steppe_1300: Object.freeze({
    "Great Khanate": "Mongol Empire",
    "Chagatai Khanate": "Mongol Empire",
  }),
  scn_trade_1650: Object.freeze({ Spain: "Spanish Habsburg" }),
  scn_world_1939: Object.freeze({ "British Raj": "United Kingdom" }),
});

export const historicalSovereignName = (scenarioId: string, sourceName: string): string =>
  sovereignAliases[scenarioId]?.[sourceName] ?? sourceName;
